Repository arduino-libraries/TFT, pull requests merged in 2021-12, with the labels that each got.

#30 Restrict supported architectures to avr and sam.
  .github/workflows/compile-examples.yml
  library.properties
Labels: enhancement

#31 Adding sync-labels workflow for sharing one set of labels across all repos.
  .github/workflows/sync-labels.yml
Labels: enhancement

#27 Add support for SAMD21 MCU boards
  .github/workflows/compile-examples.yml
  library.properties
  src/utility/Adafruit_ST7735.h
  src/utility/glcdfont.c
Labels: type: enhancement

#33 Use major version ref of `carlosperate/download-file-action`
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure
